### ISSUE TITLE
yarn test failed

### ISSUE THREAD

**Issue by AlexYIN** [khashayararyanmehr/node-express-mongoose-websockets-starter#2]
Test Suites: 4 failed, 4 total
Tests:       37 failed, 88 passed, 125 total
Snapshots:   0 total
Time:        52.423s, estimated 55s

**Comment by khashayararyanmehr** [comment]
authorization was disabled.

fixed on commit https://github.com/khashayararyanmehr/node-express-mongoose-websockets-starter/commit/f974c8574ba4abd23b5eab7307152a6394e89838
